import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Divider } from 'antd';
import Layout from '../components/Layout/Index';
import Books from '../components/books';
import Header from '../components/Header';



export default function Home({data}) {
  // const [data, setData] = useState();
  // useEffect(() => {

  //   const fetchData = async () => {
  //     const result = await axios.get("/api/books");

  //     setData(result.data);
  //   };

  //   fetchData();
  //   console.log(data);
  // }, []);
  return (
    <div >
      <Head>
        <title>کتابخانه من</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout >
<Header></Header>
        <div>
        <Divider orientation="left" style={{fontSize:20}}>جدیدترین ها </Divider>
          <Books data={data.recent}>
            
          </Books>
        </div>
       
        <div>
        <Divider orientation="left"  style={{fontSize:20}}>قدیمی تر</Divider>
          <Books data={data.old}>
            
          </Books>
        </div>
    </Layout>
    </div>
  )
}
 export async function getServerSideProps() {
  
  const data =(await axios.get("http://localhost:3000/api/books")).data
   return {
     props: {
       data
     },
   };
 }